### ISSUE TITLE
Change currency value

### ISSUE THREAD

**Issue by Jesus82** [Zmetser/angular-currency-filter#7]
Would it be possible to actually make the value conversion when an exchange rate is provided (like for example 6 € -> 6.30$)? Thanks!

**Comment by Zmetser** [comment]
Converting currencies should happen before this filter gets the value. That would be a whole other service ideally using a 3rd party api like [openexchangerates](https://openexchangerates.org) or [currencylayer](https://currencylayer.com).

Closing because value conversion is out of the scope of this filter.
